# docker-compose.yml

version: '3.9'

services:
  mariadb:
    image: mariadb
    hostname: dj_mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=domjudgebcc23
      - MYSQL_USER=domjudgebcc23
      - MYSQL_PASSWORD=domjudge_bcc23inglory
      - MYSQL_DATABASE=djfcbcc23
    command: --max-connections=1000 --max-allowed-packet=512M
    volumes:
      - /var/lib/mysql
  domjudge:
    image: domjudge/domserver
    hostname: dj_domserver
    environment:
      - CONTAINER_TIMEZONE=Asia/Jakarta
      - MYSQL_HOST=dj_mariadb
      - MYSQL_USER=domjudgebcc23
      - MYSQL_DATABASE=djfcbcc23
      - MYSQL_PASSWORD=domjudge_bcc23inglory
      - MYSQL_ROOT_PASSWORD=domjudgebcc23
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - .:/domjudge:cached
    links:
      - mariadb:mariadb
    ports:
      - 55555:80
    privileged: true
    depends_on:
      - mariadb
